<a href="https://colab.research.google.com/github/Kushalpatel3121/ML-Labs/blob/main/ML_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
#single feature x,target,prediction,feature,byes
# generate model

# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

#temperature
inputs=np.array([[73],
[91],
[87],
[102],
[69]], dtype='float32') 

# taking random values(theta1)
weight = np.array([[12],
[21],
[18],
[32],
[25]], dtype='float32')

#bias
bias = np.array([[1],[1],[1],[1],[1]],dtype='float32')

# Generate predictions

prediction = (inputs*weight) + bias

print(prediction)
MSE=np.square(np.subtract(targets,prediction)).mean()

print(MSE)


[[ 877.]
 [1912.]
 [1567.]
 [3265.]
 [1726.]]
3854896.8


In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')
from torch.utils.data import TensorDataset,DataLoader
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# print(inputs)
# print(targets)
dataset = TensorDataset(inputs,targets)
# print(dataset[:5])
#divide datasets into batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)
# tuple(train_loader)

# generate random values with ean 0 and variance 1
weights= torch.randn(1,3, requires_grad=True)
biass = torch.randn(1, requires_grad=True)

# print(weights)
# print(biass)

def model(X):
  return X @ weights.t() + biass  # '@' - for matrix multiplication

def MSE_loss(predictions, targets):
  diff = predictions - targets
  return torch.sum(diff * diff)/diff.numel() #numel return number of elements in tensor

for x,y in train_loader:
    predictions = model(x)
    print("Prediction is:\n",predictions)
    print("\Actual target is:\n",y)
    print("\nLoss is: ",MSE_loss(predictions,y))

  #training the model
epochs = 100
for i in range(epochs):
  for x,y in train_loader:
    pds = model(x)

    loss = MSE_loss(pds,y)
    loss.backward()
    # Let's update the weights
    with torch.no_grad():
        weights -= weights.grad *1e-5
        biass -= biass.grad * 1e-5
        # Set the gradients to zero
        weights.grad.zero_()
        biass.grad.zero_()
print("Loss: ",loss)

for x,y in train_loader:
  preds= model(x)
  print("\nFinal Prediction is :\n",preds)
  print("\nActual targets are :\n",y)
  break
    



Prediction is:
 tensor([[-95.0942],
        [-51.3958],
        [-38.6394],
        [-11.8155]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[119.],
        [ 81.],
        [ 56.],
        [ 22.]])

Loss is:  tensor(18366.2695, grad_fn=<DivBackward0>)
Prediction is:
 tensor([[-62.2070]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[103.]])

Loss is:  tensor(27293.3633, grad_fn=<DivBackward0>)
Loss:  tensor(1.2452, grad_fn=<DivBackward0>)

Final Prediction is :
 tensor([[ 99.1742],
        [ 25.4736],
        [ 57.7655],
        [114.8558]], grad_fn=<AddBackward0>)

Actual targets are :
 tensor([[103.],
        [ 22.],
        [ 56.],
        [119.]])


# **LAB 4_1**

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# Define dataset
train_ds = TensorDataset(inputs,targets)

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Define loss function
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

#definr utility function to train the model
def fit(num_epochs,model,loss_fn,opt):
  for epochs in range(num_epochs):
    for xb,yb in train_dl:
      #generate prediction
      pred = model(xb)
      loss = loss_fn(pred, yb)
      #perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
  print('Training loss: ', loss_fn(model(inputs), targets))
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)






Parameter containing:
tensor([[0.0368, 0.4942, 0.0673],
        [0.4179, 0.2445, 0.0446]], requires_grad=True)
Parameter containing:
tensor([ 0.2997, -0.2302], requires_grad=True)
tensor(1569.0725, grad_fn=<MseLossBackward0>)
Training loss:  tensor(31.5979, grad_fn=<MseLossBackward0>)


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704],
        [ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704],
        [ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# **Exercise 1:**
Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want).

In [ ]:
import numpy as np
import torch
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)
# Compute gradients
print("Gradient :",output.backward())
# Gradients for weights
print(w)
print(w.grad)
# Gradients for bias
print(b)
print(b.grad)
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)
# Train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([[1.7109, 0.8180, 0.1667]], requires_grad=True)
tensor([-0.9276], requires_grad=True)
Prediction : tensor([[185.9344],
        [237.4066],
        [267.1891],
        [214.9186],
        [207.3112]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor([22280.8770], grad_fn=<DivBackward0>)
Gradient : None
tensor([[1.7109, 0.8180, 0.1667]], requires_grad=True)
tensor([[25394.3320, 24254.4395, 15452.7764]])
tensor([-0.9276], requires_grad=True)
tensor([292.7039])
tensor([[1.4569, 0.5754, 0.0121]], requires_grad=True)
tensor([-0.9305], requires_grad=True)
New Loss : tensor([10189.4043], grad_fn=<DivBackward0>)
tensor([186.1981], grad_fn=<DivBackward0>)


Exercise 2: Try Linear regression on same prediction data using Tensorflow.

In [ ]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
def model1(x):
  return x @ w.t() +b
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)
print(w)
print(w.grad)
print(b)
print(b.grad)
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)


Prediction : tensor([[ 56.9378],
        [ 81.5094],
        [118.1912],
        [ 20.8060],
        [101.2179]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor(1.2789, grad_fn=<MseLossBackward0>)
tensor([[-0.1606,  0.9932,  0.1078]], requires_grad=True)
tensor([[0., 0., 0.]])
tensor([-0.9424], requires_grad=True)
tensor([0.])
tensor([48.4775], grad_fn=<DivBackward0>)


4 Ecxercise 1.1

Estimate the value of model parameters(weights and bias) and MSE Loss after training for
1000 epochs.

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-5
      biass -= biass.grad * 1e-5

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-134.8450],
        [ -85.4040],
        [-180.2136],
        [-118.8040]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 81.],
        [103.],
        [ 22.],
        [119.]])
Initial Loss:  tensor(44881.5469, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-112.8036]], grad_fn=<AddBackward0>)
Actual:  tensor([[56.]])
Initial Loss:  tensor(28494.6406, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[118.9919],
        [ 57.5586],
        [ 21.5108],
        [102.3506]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.],
        [ 56.],
        [ 22.],
        [103.]])
Final Loss:  tensor(0.7726, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[82.6352]], grad_fn=<AddBackward0>)
Actual:  tensor([[81.]])
Final Loss:  tensor(2.6739, grad_fn=<DivBackward0>)


Take the learning rate value as 0.1 and train the model. Write in brief the impact of this
learning rate on the model.

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-1
      biass -= biass.grad * 1e-1

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-17.8731],
        [-12.9354],
        [ -8.5959],
        [ -6.8420]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.],
        [ 22.],
        [ 56.],
        [ 81.]])
Initial Loss:  tensor(7960.8965, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-0.8554]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.]])
Initial Loss:  tensor(10785.9492, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[nan],
        [nan],
        [nan],
        [nan]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 22.],
        [103.],
        [ 56.],
        [ 81.]])
Final Loss:  tensor(nan, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[nan]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.]])
Final Loss:  tensor(nan, grad_fn=<DivBackward0>)


In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-7
      biass -= biass.grad * 1e-7

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))

Initial Prediction:  tensor([[-13.9154],
        [-17.9127],
        [  7.2425],
        [ -6.8972]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 22.],
        [119.],
        [103.],
        [ 56.]])
Initial Loss:  tensor(8290.1406, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-1.9804]], grad_fn=<AddBackward0>)
Actual:  tensor([[81.]])
Initial Loss:  tensor(6885.7544, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[61.5998],
        [88.6309],
        [95.4873],
        [97.8282]], grad_fn=<AddBackward0>)
Actual:  tensor([[ 56.],
        [ 81.],
        [119.],
        [103.]])
Final Loss:  tensor(167.2964, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[47.6696]], grad_fn=<AddBackward0>)
Actual:  tensor([[22.]])
Final Loss:  tensor(658.9265, grad_fn=<DivBackward0>)


Use the model to predict crop yield for apples if temperature is 70, Rain is 34 and Humidity
is 45.

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')

target = np.array([[56], [81], [119], [22], [103] ], dtype='float32')

inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)

dataset = TensorDataset(inputs, targets)

# To divide dataset into the batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)

# torch,randn generates random value matrix such that mean = 0 and variance = 1

# 1x3 random value matrix
weight = torch.randn(1,3, requires_grad=True)

# 1x1 random value matrix
biass = torch.rand(1, requires_grad=True)

def mse_loss_function(prediction, target):
  difference = prediction - target
  difference_square = difference * difference
  return torch.sum(difference_square) /difference.numel() 



def model(X):
  return X @ weight.T + biass # input matrix and weight matrix multiplication and add bias

for x, y in train_loader:
  prediction = model(x)

  print("Initial Prediction: ", prediction)
  print("Actual: ", y)

  print("Initial Loss: ", mse_loss_function(prediction, y))


# Training

epochs = 1000

for i in range(epochs):

  for x,y in train_loader:
    preds = model(x)
    loss = mse_loss_function(preds, y)

    loss.backward()

    with torch.no_grad():
      weight -= weight.grad * 1e-5
      biass -= biass.grad * 1e-5

      weight.grad.zero_()
      biass.grad.zero_()





# Final
for x, y in train_loader:
  prediction = model(x)

  print()
  print()

  print("Final Prediction: ", prediction)
  print("Actual: ", y)

  print("Final Loss: ", mse_loss_function(prediction, y))
pred = model(torch.from_numpy(np.array([70, 34, 45], dtype='float32')))
pred


Initial Prediction:  tensor([[-198.6473],
        [-226.7035],
        [-229.3315],
        [-175.7090]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.],
        [119.],
        [ 81.],
        [ 56.]])
Initial Loss:  tensor(90124.1719, grad_fn=<DivBackward0>)
Initial Prediction:  tensor([[-215.0600]], grad_fn=<AddBackward0>)
Actual:  tensor([[22.]])
Initial Loss:  tensor(56197.4648, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[101.2179],
        [ 81.5094],
        [ 20.8060],
        [ 56.9378]], grad_fn=<AddBackward0>)
Actual:  tensor([[103.],
        [ 81.],
        [ 22.],
        [ 56.]])
Final Loss:  tensor(1.4351, grad_fn=<DivBackward0>)


Final Prediction:  tensor([[118.1912]], grad_fn=<AddBackward0>)
Actual:  tensor([[119.]])
Final Loss:  tensor(0.6541, grad_fn=<DivBackward0>)


tensor([31.4602], grad_fn=<AddBackward0>)